// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:18a29522-97b5-44f5-aff8-9b97d0ccb12d',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'seushow-hosting-mobilehub-1424062600',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dph9i69ytjc1.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a9765b413b8c4fbca3dbc439a5a4ac84',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '01b50b8b-3aa8-4624-8afc-98ecd3033e20',
    'aws_project_name': 'seushow',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'seushow-mobilehub-1424062600',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-1_tLM1KjTOM',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5uq9f2kbdrc8vsc4k1c0mdh528',
}

export default awsmobile;
